### ISSUE TITLE
Add Presentation Mode

### ISSUE THREAD

**Issue by TinasheMzondiwa** [Faith-UnFeigned/cis-web#72]
Similar to what we have in the Android app we'd like to have a presentation mode.

- Add presentation icon to enter or exit full screen mode
- Break up the hymn into individual verses/sections 
- Display one section at a time 
- Add next and previous icons/ buttons to go to the next or previous section 
- Repeat choruses

**Comment by YewoMhango** [comment]
Thanks, noted
